{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
  {{- with .Values.mysql.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}
{{- end }}